### PR TITLE
[PLA-1931] Support require signature

### PR DESCRIPTION
**Pull request by enjinabner**
### **PR Type**
Enhancement

___

### **Description**
- Added descriptions for `require_signature` and its `signature` field in `lang/en/input_type.php`.
- Added `requireSignature` field to the `DispatchRuleInputType` GraphQL input type.
- Created new `RequireSignatureInputType` class with defined attributes and fields.
- Fixed return value in `RequireSignatureParams`'s `toArray` method to return the signature.
- Added `RequireSignatureParams` to the list of imports and included `requireSignature` handling in `getDispatchRulesParams` method in `Substrate.php`.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>input_type.php</strong><dd><code>Add descriptions for require_signature fields</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

lang/en/input_type.php

<li>Added descriptions for <code>require_signature</code> and its <code>signature</code> field.<br>

</details>

  </td>
  <td><a href="https://github.com/enjin/platform-fuel-tanks/pull/60/files#diff-7d0779276a282cc2c2f2b9eb2a8f659e8e119f47d066bd06d1431d9391530794">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>DispatchRuleInputType.php</strong><dd><code>Add requireSignature field to DispatchRuleInputType</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/GraphQL/Types/Input/DispatchRuleInputType.php

- Added `requireSignature` field to the GraphQL input type.

</details>

  </td>
  <td><a href="https://github.com/enjin/platform-fuel-tanks/pull/60/files#diff-0bd09b94799a8250e15b2ebe58d128eaf8ab4d375bf30d69e4756eac75d3be18">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>RequireSignatureInputType.php</strong><dd><code>Create RequireSignatureInputType class</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/GraphQL/Types/Input/RequireSignatureInputType.php

<li>Created new <code>RequireSignatureInputType</code> class.<br> <li> Defined attributes and fields for <code>RequireSignatureInputType</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/enjin/platform-fuel-tanks/pull/60/files#diff-308b1293fdc04b201c16b3283917e6c85b25dfc248d0ae038115b0898c644e9f">+32/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Substrate.php</strong><dd><code>Add requireSignature handling in getDispatchRulesParams</code>&nbsp; &nbsp; </dd></summary>
<hr>

src/Services/Blockchain/Implemetations/Substrate.php

<li>Added <code>RequireSignatureParams</code> to the list of imports.<br> <li> Included <code>requireSignature</code> handling in <code>getDispatchRulesParams</code> method.<br>

</details>

  </td>
  <td><a href="https://github.com/enjin/platform-fuel-tanks/pull/60/files#diff-5fcd78bf882bf88b8b64927ed6d5c882dbc66ad25ae940f0d63d79bc12398942">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>RequireSignatureParams.php</strong><dd><code>Fix return value in RequireSignatureParams toArray method</code></dd></summary>
<hr>

src/Models/Substrate/RequireSignatureParams.php

- Fixed return value in `toArray` method to return the signature.

</details>

  </td>
  <td><a href="https://github.com/enjin/platform-fuel-tanks/pull/60/files#diff-250c2896b1829bdf48476115750ad459e2756da1859c1bed0f6de32123b136c9">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by enjinabner** [comment]
I will create another PR for unit test, need to check with leo how to update local network

**Review by v16Studios — DISMISSED** [review]

**Review by leonardocustodio — COMMENTED** [review]
I believe you can add a validation in the field to be a hexadecimal string of 32 size.

**Comment by enjinabner** [comment]
> I believe you can add a validation in the field to be a hexadecimal string of 32 size.

Do we have an existing rule for that or checking strlen with size 32 is enough?

**Comment by leonardocustodio** [comment]
There is a hex rule that you can pass the size.

**Comment by enjinabner** [comment]
> There is a hex rule on platform core that you can pass the size.

I've had this but can't seem to make it pass. Is this correct?
```
return [
            'signature' => [
                'type' => GraphQL::type('String!'),
                'description' => __('enjin-platform-fuel-tanks::input_type.require_signature.field.signature'),
                'rules' => [new ValidHex(Hex::MAX_UINT32)],
            ],
        ];
```

**Comment by leonardocustodio** [comment]
It is just ValidHex(32), uint32 would be the size of an uint32 variable

**Review by leonardocustodio — APPROVED** [review]

**Pull request merged**
